//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.ReceiptItems = new HashSet<ReceiptItems>();
        }
    
        public int ReceiptID { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsPaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItems> ReceiptItems { get; set; }
        public virtual Shifts Shifts { get; set; }
    }
}
