//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeCards
    {
        public int RecipeCardID { get; set; }
        public int ProductID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
